imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            datetime_functions:
                 convert_tz: DoctrineExtensions\Query\Mysql\ConvertTz
                 date: DoctrineExtensions\Query\Mysql\Date
                 date_format: DoctrineExtensions\Query\Mysql\DateFormat
                 dateadd: DoctrineExtensions\Query\Mysql\DateAdd
                 datesub: DoctrineExtensions\Query\Mysql\DateSub
                 datediff: DoctrineExtensions\Query\Mysql\DateDiff
                 day: DoctrineExtensions\Query\Mysql\Day
                 dayname: DoctrineExtensions\Query\Mysql\DayName
                 dayofweek: DoctrineExtensions\Query\Mysql\DayOfWeek
                 dayofyear: DoctrineExtensions\Query\Mysql\DayOfYear
                 div: DoctrineExtensions\Query\Mysql\Div
                 from_unixtime: DoctrineExtensions\Query\Mysql\FromUnixtime
                 hour: DoctrineExtensions\Query\Mysql\Hour
                 last_day: DoctrineExtensions\Query\Mysql\LastDay
                 minute: DoctrineExtensions\Query\Mysql\Minute
                 now: DoctrineExtensions\Query\Mysql\Now
                 month: DoctrineExtensions\Query\Mysql\Month
                 monthname: DoctrineExtensions\Query\Mysql\MonthName
                 second: DoctrineExtensions\Query\Mysql\Second
                 strtodate: DoctrineExtensions\Query\Mysql\StrToDate
                 time: DoctrineExtensions\Query\Mysql\Time
                 timediff: DoctrineExtensions\Query\Mysql\TimeDiff
                 timestampadd: DoctrineExtensions\Query\Mysql\TimestampAdd
                 timestampdiff: DoctrineExtensions\Query\Mysql\TimestampDiff
                 timetosec: DoctrineExtensions\Query\Mysql\TimeToSec
                 week: DoctrineExtensions\Query\Mysql\Week
                 weekday: DoctrineExtensions\Query\Mysql\WeekDay
                 year: DoctrineExtensions\Query\Mysql\Year
                 yearweek: DoctrineExtensions\Query\Mysql\YearWeek
                 unix_timestamp: DoctrineExtensions\Query\Mysql\UnixTimestamp

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

ekino_wordpress:
    globals: # If you have some custom global variables that WordPress needs
        - wp_global_variable_1
        - wp_global_variable_2
    table_prefix: "wp_" # If you have a specific Wordpress table prefix
    wordpress_directory: "%kernel.root_dir%/../../wordpress"
    load_twig_extension: true # If you want to enable native WordPress functions (ie : get_option() => wp_get_option())
    enable_wordpress_listener: false # If you want to disable the WordPress request listener
    security:
        firewall_name: "secured_area" # This is the firewall default name
        login_url: "/wp-login.php" # Absolute URL to the wordpress login page

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
            address: you@example.com
            sender_name: You